# Generated by Django 3.0.6 on 2020-05-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_id', models.CharField(max_length=200)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdn.Controller')),
            ],
        ),
    ]
