# Generated by Django 3.0.6 on 2020-05-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn', '0003_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='name',
            field=models.CharField(default='aaa', max_length=200),
        ),
    ]
